import React from 'react';
import GoogleBar from './GoogleBar.jsx';
import LoadingDots from './LoadingDots.jsx';
import gdgLogo from '../assets/gdg-logo.png';
export function palette(darkMode){return{bg:darkMode?'#121212':'#F8F9FA',card:darkMode?'#1E1E1E':'#FFFFFF',alt:darkMode?'#2A2A2A':'#F1F3F4',border:darkMode?'#333333':'#E0E0E0',text:darkMode?'#E0E0E0':'#1C1B1F',muted:darkMode?'#AAAAAA':'#5F6368',secondary:darkMode?'#CCCCCC':'#3C4043'};}
export function Shell({darkMode,children,className=''}){const t=palette(darkMode);return <div className={`min-h-screen flex flex-col ${className}`} style={{backgroundColor:t.bg,color:t.text}}><div className="flex flex-1 min-h-0 flex-col">{children}</div><GoogleBar/></div>}
export function LogoMark({size=38}){return <img src={gdgLogo} alt="" width={size} className="h-auto flex-shrink-0 object-contain" aria-hidden="true"/>}
export function Brand({darkMode,small=false,admin=false}){const t=palette(darkMode);return <div className="flex items-center gap-3"><LogoMark size={small?32:38}/><div><div className="font-['DM_Sans'] font-semibold leading-tight tracking-tight" style={{color:t.text,fontSize:small?14:15}}>GDG KAU{admin?' Admin':''}</div><div className="font-['Roboto'] text-[11px] leading-tight" style={{color:t.muted}}>King Abdulaziz University</div></div></div>}
export function Card({darkMode,children,className=''}){const t=palette(darkMode);return <section className={`rounded-[16px] border p-5 sm:p-6 shadow-sm ${className}`} style={{backgroundColor:t.card,borderColor:t.border}}>{children}</section>}
export function Button({children,variant='primary',className='',...props}){const styles={primary:{background:'#3A7CF5',color:'#fff',boxShadow:'0 2px 8px rgba(58,124,245,.3)'},secondary:{background:'transparent',color:'#3A7CF5',border:'1.5px solid #3A7CF5'},danger:{background:'#EA4335',color:'#fff',boxShadow:'0 2px 6px rgba(234,67,53,.25)'},quiet:{background:'var(--surface-alt)',color:'var(--text-secondary)'}};return <button {...props} className={`gdg-button px-5 py-2.5 rounded-[10px] text-[14px] font-semibold font-['DM_Sans'] transition-all duration-150 active:scale-[0.97] disabled:opacity-50 disabled:cursor-not-allowed ${className}`} data-variant={variant} style={{...styles[variant],...props.style}}>{children}</button>}
export function Input({label,darkMode,textarea=false,...props}){const t=palette(darkMode);const C=textarea?'textarea':'input';return <label className="flex flex-col gap-1.5 text-[13px] font-medium font-['Roboto']" style={{color:t.secondary}}>{label}<C {...props} className={`w-full px-4 py-3 rounded-[8px] text-[15px] font-['Roboto'] gdg-input ${props.className||''}`} style={{background:t.card,color:t.text,borderColor:t.border,minHeight:textarea?120:undefined,...props.style}}/></label>}
export function Select({label,darkMode,children,...props}){const t=palette(darkMode);return <label className="flex flex-col gap-1.5 text-[13px] font-medium font-['Roboto']" style={{color:t.secondary}}>{label}<select {...props} className="w-full px-4 py-3 rounded-[8px] text-[15px] font-['Roboto'] gdg-input" style={{background:t.card,color:t.text,borderColor:t.border}}>{children}</select></label>}
export function Pill({children,kind='info',darkMode,color}){const colors={info:['#E8F0FE','#1967D2','#4285F4'],success:['#E8F5E9','#2E7D32','#34A853'],warning:['#FFF8E1','#E65100','#FBBC04'],error:['#FFEBEE','#B71C1C','#EA4335'],neutral:['#F1F3F4','#5F6368','#9AA0A6']};const [bg,fg,dot]=colors[kind],accent=color||dot;return <span className="inline-flex items-center gap-2 rounded-[10px] px-3 py-1.5 text-[12px] font-semibold font-['Roboto']" style={{background:color?`${color}${darkMode?'26':'1A'}`:darkMode?'#2A2A2A':bg,color:color||darkMode?accent:fg}}><span className="w-2 h-2 rounded-full" style={{background:accent}}/>{children}</span>}
export function ErrorBanner({message,darkMode}){if(!message)return null;return <div className="rounded-[10px] border px-4 py-3 text-[13px] font-['Roboto']" style={{background:darkMode?'rgba(234,67,53,.12)':'#FFEBEE',borderColor:darkMode?'rgba(234,67,53,.35)':'#FFCDD2',color:darkMode?'#FCA5A5':'#C62828'}}>{message}</div>}
export function Busy({darkMode}){return <LoadingDots darkMode={darkMode}/>}
export function Empty({title,detail,darkMode}){const t=palette(darkMode);return <div className="flex flex-col items-center justify-center text-center py-12 gap-3"><div className="w-14 h-14 rounded-full flex items-center justify-center" style={{background:darkMode?'#1A2E4B':'#E8F0FE',color:'#3A7CF5'}}><svg width="30" height="30" viewBox="0 0 30 30" fill="none"><circle cx="15" cy="15" r="11" stroke="currentColor" strokeWidth="1.5"/><path d="M10 15h10M15 10v10" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round"/></svg></div><strong className="font-['DM_Sans'] text-[16px]">{title}</strong><p className="font-['Roboto'] text-[14px] max-w-sm" style={{color:t.muted}}>{detail}</p></div>}
export function ThemeToggle({darkMode,onClick}){return <button onClick={onClick} className="w-9 h-9 rounded-[8px] border flex items-center justify-center transition-colors" style={{borderColor:darkMode?'#333333':'#E0E0E0',color:darkMode?'#FBBC04':'#5F6368',background:darkMode?'#1E1E1E':'#FFFFFF'}} aria-label="Toggle theme">{darkMode?<svg width="17" height="17" viewBox="0 0 17 17" fill="none"><circle cx="8.5" cy="8.5" r="3" stroke="currentColor" strokeWidth="1.4"/><path d="M8.5 1v2M8.5 14v2M1 8.5h2M14 8.5h2M3.2 3.2l1.4 1.4M12.4 12.4l1.4 1.4M13.8 3.2l-1.4 1.4M4.6 12.4l-1.4 1.4" stroke="currentColor" strokeWidth="1.4" strokeLinecap="round"/></svg>:<svg width="17" height="17" viewBox="0 0 17 17" fill="none"><path d="M14.5 10.6A6.2 6.2 0 0 1 6.4 2.5a6.2 6.2 0 1 0 8.1 8.1Z" stroke="currentColor" strokeWidth="1.4" strokeLinejoin="round"/></svg>}</button>}
export function DecorativePattern({darkMode}){return <svg className="absolute inset-0 w-full h-full pointer-events-none" viewBox="0 0 700 700" fill="none" preserveAspectRatio="xMidYMid slice" style={{opacity:darkMode?.12:.055}}><circle cx="85" cy="610" r="180" stroke="#4285F4" strokeWidth="2"/><circle cx="610" cy="90" r="210" stroke="#EA4335" strokeWidth="2"/><circle cx="610" cy="90" r="140" stroke="#FBBC04" strokeWidth="2"/><circle cx="110" cy="610" r="105" stroke="#34A853" strokeWidth="2"/></svg>}
