import { existsSync, mkdirSync, readFileSync, writeFileSync, appendFileSync, openSync } from 'node:fs';
import { spawn, spawnSync } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import net from 'node:net';
import path from 'node:path';
import process from 'node:process';

const root=process.cwd();
const envPath=path.join(root,'.env');
const localRoot=path.join(root,'.local');
const dataDir=path.join(localRoot,'pgdata');
const logPath=path.join(localRoot,'postgres.log');
const port=55432;
const localPassword='gdg-admin-local';

function parseEnv(text){return Object.fromEntries(text.split(/\r?\n/).map(line=>line.match(/^([^#=]+)=(.*)$/)).filter(Boolean).map(m=>[m[1].trim(),m[2].trim()]));}
function command(name){
  if(process.env.POSTGRES_BIN)return path.join(process.env.POSTGRES_BIN,process.platform==='win32'?`${name}.exe`:name);
  if(process.platform==='win32'){
    for(const version of ['18','17','16','15']){const candidate=`C:\\Program Files\\PostgreSQL\\${version}\\bin\\${name}.exe`;if(existsSync(candidate))return candidate;}
  }
  return name;
}
function run(binary,args,options={}){const result=spawnSync(binary,args,{cwd:root,encoding:'utf8',...options});if(result.status!==0)throw new Error(`${path.basename(binary)} failed:\n${result.stderr||result.stdout}`);return result;}
function waitForPort(host,dbPort,timeoutMs=12000){return new Promise((resolve,reject)=>{const started=Date.now();const attempt=()=>{const socket=net.createConnection({host,port:dbPort});socket.once('connect',()=>{socket.destroy();resolve()});socket.once('error',()=>{socket.destroy();if(Date.now()-started>timeoutMs)reject(new Error(`PostgreSQL did not start. See ${logPath}`));else setTimeout(attempt,180)});};attempt();});}
function canConnect(host,dbPort){return new Promise(resolve=>{const socket=net.createConnection({host,port:dbPort});socket.once('connect',()=>{socket.destroy();resolve(true)});socket.once('error',()=>{socket.destroy();resolve(false)});socket.setTimeout(500,()=>{socket.destroy();resolve(false)});});}

mkdirSync(localRoot,{recursive:true});
let env=existsSync(envPath)?parseEnv(readFileSync(envPath,'utf8')):null;
let useLocalDb=!env;
if(!env){
  const sessionSecret=randomBytes(32).toString('hex');
  const contents=[
    '# Generated by npm run dev for local development only.',
    `DATABASE_URL=postgres://postgres@127.0.0.1:${port}/gdg_event`,
    `ADMIN_PASSWORD=${localPassword}`,
    `SESSION_SECRET=${sessionSecret}`,
    'PORT=5001',
    'PUBLIC_ORIGIN=http://localhost:5173',
    'VITE_API_URL=http://localhost:5001',
    'GDG_LOCAL_DATABASE=true',''
  ].join('\n');
  writeFileSync(envPath,contents,{encoding:'utf8',flag:'wx'});
  env=parseEnv(contents);
  console.log('Created .env for local development.');
}else{
  useLocalDb=env.GDG_LOCAL_DATABASE==='true';
}

let postgres=null;
let ownsDatabase=false;
if(useLocalDb){
  const initdb=command('initdb');const postgresBin=command('postgres');const createdb=command('createdb');
  if(!existsSync(path.join(dataDir,'PG_VERSION'))){
    console.log('Creating a project-local PostgreSQL database…');
    mkdirSync(dataDir,{recursive:true});
    run(initdb,['-D',dataDir,'--auth=trust','--encoding=UTF8','--username=postgres','--no-instructions']);
  }
  if(!await canConnect('127.0.0.1',port)){
    const logFd=openSync(logPath,'a');
    postgres=spawn(postgresBin,['-D',dataDir,'-p',String(port),'-h','127.0.0.1'],{cwd:root,stdio:['ignore',logFd,logFd],windowsHide:true});
    ownsDatabase=true;
    postgres.once('exit',code=>{if(code&&code!==0)console.error(`Local PostgreSQL stopped with code ${code}. See ${logPath}`)});
    await waitForPort('127.0.0.1',port);
  }
  let created;
  for(let attempt=0;attempt<40;attempt++){
    created=spawnSync(createdb,['-h','127.0.0.1','-p',String(port),'-U','postgres','gdg_event'],{cwd:root,encoding:'utf8'});
    if(created.status===0||/already exists/i.test(created.stderr||''))break;
    if(!/starting up|no response|connection refused/i.test(created.stderr||''))break;
    await new Promise(resolve=>setTimeout(resolve,200));
  }
  if(created.status!==0&&!/already exists/i.test(created.stderr||'')){
    if(ownsDatabase&&postgres?.exitCode===null)postgres.kill('SIGTERM');
    throw new Error(`createdb failed:\n${created.stderr||created.stdout}`);
  }
}

console.log(`Admin password: ${env.ADMIN_PASSWORD}`);
console.log('Attendee: http://localhost:5173/  Screen: /screen  Admin: /admin');

const npm=process.platform==='win32'?'npm.cmd':'npm';
let app;
try{
  app=spawn(npm,['run','dev:app'],{cwd:root,stdio:'inherit',env:{...process.env,...env},windowsHide:true,shell:process.platform==='win32'});
}catch(error){
  if(ownsDatabase&&postgres?.exitCode===null)postgres.kill('SIGTERM');
  throw error;
}
let stopping=false;
function stop(signal='SIGTERM'){
  if(stopping)return;stopping=true;
  if(app.exitCode===null)app.kill(signal);
  if(ownsDatabase&&postgres?.exitCode===null)postgres.kill(signal);
}
process.on('SIGINT',()=>stop('SIGINT'));
process.on('SIGTERM',()=>stop('SIGTERM'));
app.on('exit',code=>{stop();process.exitCode=code??0});
