import { randomUUID } from 'node:crypto';
import { pool, tx } from '../db/index.js';
import { fail, normalizeName, requireStatus, score, selectRandom, uuid, validText } from './logic.js';

const one = async (db, sql, args = []) => (await db.query(sql, args)).rows[0];
const all = async (db, sql, args = []) => (await db.query(sql, args)).rows;
async function locked(db) { return one(db, 'SELECT * FROM event_state WHERE id=1 FOR UPDATE'); }
function needId(id) { if (!uuid(id)) fail(400, 'Invalid identifier.'); return id; }
function needTeamId(teamId) { const id = Number(teamId); if (![1, 2].includes(id)) fail(400, 'Choose a team.'); return id; }
async function attendee(db, id) { const row = await one(db, 'SELECT a.*,t.name AS team_name,t.color AS team_color FROM attendees a JOIN teams t ON t.id=a.team_id WHERE a.id=$1', [needId(id)]); if (!row) fail(404, 'Attendee not found.'); return row; }
async function teamSpeakerState(db, teamId, lock = false) { const id = needTeamId(teamId); const row = await one(db, `SELECT * FROM team_speaker_state WHERE team_id=$1${lock ? ' FOR UPDATE' : ''}`, [id]); if (!row) fail(409, 'Speaker screen is not initialized for this team.'); return row; }
async function currentSpeaker(db, state) { if (!state?.speaker_session_id) fail(409, 'No current speaker for this team.'); return one(db, 'SELECT ss.*,a.name AS speaker_name,t.name AS team_name,t.color AS team_color,p.prompt_text FROM speaker_sessions ss JOIN attendees a ON a.id=ss.speaker_id JOIN teams t ON t.id=ss.team_id LEFT JOIN speaker_prompts p ON p.id=ss.prompt_id WHERE ss.id=$1', [state.speaker_session_id]); }
async function currentRound(db, state) { if (!state.scenario_round_id) fail(409, 'No current scenario round.'); return one(db, 'SELECT r.*,sc.title,sc.scenario_text FROM scenario_rounds r JOIN scenarios sc ON sc.id=r.scenario_id WHERE r.id=$1', [state.scenario_round_id]); }
const changed = (io, event = 'event:changed') => { io.emit(event); if (event !== 'event:changed') io.emit('event:changed'); };

async function randomizeScenarioAnswers(db, roundId) {
  const rows = await all(db, 'SELECT id FROM scenario_answers WHERE round_id=$1', [roundId]);
  const shuffled = selectRandom(rows, rows.length);
  for (let index = 0; index < shuffled.length; index++) await db.query('UPDATE scenario_answers SET display_order=$2 WHERE id=$1', [shuffled[index].id, 100000 + index]);
  for (let index = 0; index < shuffled.length; index++) await db.query('UPDATE scenario_answers SET display_order=$2 WHERE id=$1', [shuffled[index].id, index]);
}

async function advanceExpiredScenario() {
  const active = await one(pool, `SELECT r.id FROM event_state es JOIN scenario_rounds r ON r.id=es.scenario_round_id WHERE es.id=1 AND es.activity='SCENARIO' AND r.status='COLLECTING' AND r.ends_at<=now()`);
  if (!active) return false;
  return tx(async db => {
    const state = await locked(db);
    if (!state.scenario_round_id) return false;
    const round = await currentRound(db, state);
    if (round.status !== 'COLLECTING' || new Date(round.ends_at).getTime() > Date.now()) return false;
    await randomizeScenarioAnswers(db, round.id);
    await db.query("UPDATE scenario_rounds SET status='OPEN' WHERE id=$1", [round.id]);
    await db.query("UPDATE event_state SET screen_view='SCENARIO_VOTING',updated_at=now() WHERE id=1", []);
    return true;
  });
}

async function speakerData(db, state, viewer, origin, includePrivate) {
  if (!state.speaker_session_id) return null;
  const speaker = await currentSpeaker(db, state);
  const votes = await one(db, 'SELECT count(*)::int AS count FROM speaker_votes WHERE session_id=$1', [speaker.id]);
  const isSpeaker = viewer?.id === speaker.speaker_id;
  const data = { id: speaker.id, name: speaker.speaker_name, teamId: speaker.team_id, teamName: speaker.team_name, teamColor: speaker.team_color, prompt: speaker.prompt_text, status: speaker.status, voteCount: votes.count, score: speaker.status === 'REVEALED' ? Number(speaker.displayed_score) : null, isSpeaker, canVote: speaker.status === 'OPEN' && !!viewer && viewer.team_id === speaker.team_id && !isSpeaker };
  if (includePrivate && speaker.status === 'SELECTED') data.qrUrl = `${origin}/?confirm=${speaker.qr_token}`;
  if (viewer) data.hasVoted = !!await one(db, 'SELECT 1 FROM speaker_votes WHERE session_id=$1 AND attendee_id=$2', [speaker.id, viewer.id]);
  return data;
}

export async function register({ name, teamId }) { const value = normalizeName(name); if (value.length < 2 || value.length > 80) fail(400, 'Enter a name between 2 and 80 characters.'); if (![1, 2].includes(Number(teamId))) fail(400, 'Choose a team.'); const id = randomUUID(); try { return await one(pool, 'INSERT INTO attendees(id,name,name_key,team_id) VALUES($1,$2,$3,$4) RETURNING id,name,team_id,dark_mode', [id, value, value.toLocaleLowerCase(), Number(teamId)]); } catch (error) { if (error.code === '23505') fail(409, 'This name is already registered. Please enter your full two-part name.'); throw error; } }
export async function getAttendee(id) { return attendee(pool, id); }
export async function setTheme(id, darkMode) { if (typeof darkMode !== 'boolean') fail(400, 'Invalid theme.'); return one(pool, 'UPDATE attendees SET dark_mode=$2 WHERE id=$1 RETURNING id,dark_mode', [needId(id), darkMode]); }

export async function publicState(attendeeId, origin, includePrivate = false, screenTeamId = null) {
  await advanceExpiredScenario();
  const state = await one(pool, 'SELECT * FROM event_state WHERE id=1'), teams = await all(pool, 'SELECT * FROM teams ORDER BY id');
  let viewer = null; if (attendeeId && uuid(attendeeId)) viewer = await one(pool, 'SELECT id,name,team_id,dark_mode FROM attendees WHERE id=$1', [attendeeId]);
  const teamStates = await all(pool, 'SELECT * FROM team_speaker_state ORDER BY team_id'), speakers = [];
  for (const teamState of teamStates) { const speaker = await speakerData(pool, teamState, viewer, origin, includePrivate); if (speaker) speakers.push(speaker); }
  const requestedTeam = screenTeamId == null ? null : needTeamId(screenTeamId), contextTeam = requestedTeam ?? viewer?.team_id ?? null;
  const speaker = contextTeam ? speakers.find(item => item.teamId === Number(contextTeam)) || null : null, speakerScreen = contextTeam ? teamStates.find(item => item.team_id === Number(contextTeam)) : null;
  const scenarioActive = state.activity === 'SCENARIO' && !!state.scenario_round_id;
  const visibleSpeakers = includePrivate ? speakers : speaker ? [speaker] : [];
  const data = { eventName: state.event_name, activity: scenarioActive ? 'SCENARIO' : speaker ? 'SPEAKER' : 'NONE', globalActivity: state.activity, screenView: requestedTeam ? speakerScreen?.screen_view || 'WAITING' : state.screen_view, screenDarkMode: state.screen_dark_mode, screenTeamId: requestedTeam, teams, viewer, speaker, speakers: visibleSpeakers, speakerScreens: includePrivate ? teamStates.map(item => ({ teamId: item.team_id, screenView: item.screen_view, active: !!item.speaker_session_id })) : undefined };
  if (state.scenario_round_id) { const round = await currentRound(pool, state), canSubmit = viewer ? !!await one(pool, 'SELECT 1 FROM scenario_round_participants WHERE round_id=$1 AND attendee_id=$2', [round.id, viewer.id]) : false, submitted = viewer ? !!await one(pool, 'SELECT 1 FROM scenario_answers WHERE round_id=$1 AND attendee_id=$2', [round.id, viewer.id]) : false, voted = viewer ? !!await one(pool, 'SELECT 1 FROM scenario_votes WHERE round_id=$1 AND attendee_id=$2', [round.id, viewer.id]) : false; const answers = ['OPEN', 'CLOSED', 'REVEALED'].includes(round.status) ? await all(pool, `SELECT a.id,a.answer_text,a.display_order,${viewer ? 'a.attendee_id=$2 AS is_own' : 'false AS is_own'},${round.status === 'REVEALED' ? 'at.name AS author, (SELECT count(*)::int FROM scenario_votes v WHERE v.answer_id=a.id) AS votes' : 'NULL::text AS author, NULL::int AS votes'} FROM scenario_answers a JOIN attendees at ON at.id=a.attendee_id WHERE a.round_id=$1 ORDER BY ${round.status === 'REVEALED' ? 'votes DESC, a.display_order' : 'a.display_order'}`, viewer ? [round.id, viewer.id] : [round.id]) : []; data.scenario = { id: round.id, title: round.title, text: round.scenario_text, status: round.status, canSubmit, submitted, voted, answers, durationSeconds: round.duration_seconds, startedAt: round.started_at, endsAt: round.ends_at }; }
  data.speakerLeaderboard = await all(pool, "SELECT a.name, ss.team_id, ss.displayed_score::float AS score FROM speaker_sessions ss JOIN attendees a ON a.id=ss.speaker_id WHERE ss.status='REVEALED' ORDER BY ss.team_id,ss.displayed_score DESC,ss.created_at");
  data.teamPerformance = await all(pool, "SELECT t.id AS team_id,t.name,t.color,round(avg(ss.displayed_score),2)::float AS average FROM teams t LEFT JOIN speaker_sessions ss ON ss.team_id=t.id AND ss.status='REVEALED' GROUP BY t.id ORDER BY t.id");
  data.scenarioLeaderboard = await all(pool, "SELECT a.name,coalesce(count(v.answer_id),0)::int AS points FROM attendees a JOIN scenario_answers an ON an.attendee_id=a.id JOIN scenario_rounds r ON r.id=an.round_id AND r.status='REVEALED' LEFT JOIN scenario_votes v ON v.answer_id=an.id GROUP BY a.id ORDER BY points DESC,a.name");
  return data;
}

export async function adminSnapshot(origin, connectedCount = 0) {
  const state = await publicState(null, origin, true);
  const [attendees, scenarios, counts, played, answers, speakerPrompts] = await Promise.all([all(pool, "SELECT a.id,a.name,a.team_id,EXISTS(SELECT 1 FROM speaker_sessions s WHERE s.speaker_id=a.id AND s.status<>'CANCELLED') AS spoke,EXISTS(SELECT 1 FROM scenario_answers an JOIN scenario_rounds r ON r.id=an.round_id WHERE an.attendee_id=a.id AND r.status<>'CANCELLED') AS played FROM attendees a ORDER BY a.name"), all(pool, 'SELECT * FROM scenarios ORDER BY created_at DESC'), all(pool, 'SELECT team_id,count(*)::int AS count FROM attendees GROUP BY team_id'), one(pool, 'SELECT count(*)::int AS count FROM attendees'), state.scenario ? all(pool, 'SELECT an.id,an.attendee_id,a.name,an.answer_text,an.approved,an.display_order FROM scenario_answers an JOIN attendees a ON a.id=an.attendee_id WHERE an.round_id=$1 ORDER BY an.created_at', [state.scenario.id]) : [], all(pool, "SELECT p.id,p.prompt_text,p.created_at,coalesce(array_agg(DISTINCT ss.team_id) FILTER (WHERE ss.team_id IS NOT NULL),'{}')::smallint[] AS used_team_ids FROM speaker_prompts p LEFT JOIN speaker_sessions ss ON ss.prompt_id=p.id GROUP BY p.id ORDER BY cardinality(coalesce(array_agg(DISTINCT ss.team_id) FILTER (WHERE ss.team_id IS NOT NULL),'{}')::smallint[]),p.created_at DESC")]);
  Object.assign(state, { attendees, scenarios, teamCounts: counts, attendeeCount: played.count, connectedCount, answers, speakerPrompts, activity: state.globalActivity });
  for (const speaker of state.speakers) { const eligible = await one(pool, 'SELECT count(*)::int AS count FROM attendees WHERE team_id=$1 AND id<>(SELECT speaker_id FROM speaker_sessions WHERE id=$2)', [speaker.teamId, speaker.id]); speaker.eligibleCount = eligible.count; }
  if (state.scenario) { const eligible = await one(pool, 'SELECT count(*)::int AS count FROM attendees at WHERE EXISTS(SELECT 1 FROM scenario_answers an WHERE an.round_id=$1 AND an.attendee_id<>at.id)', [state.scenario.id]), votes = await one(pool, 'SELECT count(*)::int AS count FROM scenario_votes WHERE round_id=$1', [state.scenario.id]); state.scenario.eligibleCount = eligible.count; state.scenario.voteCount = votes.count; state.scenario.answerCount = answers.length; }
  state.defaultParticipants = (await one(pool, 'SELECT default_participants FROM event_state WHERE id=1')).default_participants; return state;
}

export async function settings(input, io) { await tx(async db => { await locked(db); const eventName = validText(input.eventName, 100, 'Event name'), count = Number(input.defaultParticipants); if (!Number.isInteger(count) || count < 2 || count > 30) fail(400, 'Participant count must be 2–30.'); await db.query('UPDATE event_state SET event_name=$1,default_participants=$2,updated_at=now() WHERE id=1', [eventName, count]); for (const team of input.teams || []) { if (![1, 2].includes(Number(team.id)) || !/^#[0-9a-f]{6}$/i.test(team.color)) fail(400, 'Invalid team.'); await db.query('UPDATE teams SET name=$2,color=$3 WHERE id=$1', [Number(team.id), validText(team.name, 40, 'Team name'), team.color]); } }); changed(io); }
export async function adminTheme(darkMode) { if (typeof darkMode !== 'boolean') fail(400, 'Invalid theme.'); await pool.query('UPDATE event_state SET admin_dark_mode=$1 WHERE id=1', [darkMode]); }
export async function getAdminTheme() { return (await one(pool, 'SELECT admin_dark_mode FROM event_state WHERE id=1')).admin_dark_mode; }
export async function screenTheme(darkMode, io) { if (typeof darkMode !== 'boolean') fail(400, 'Invalid screen theme.'); await pool.query('UPDATE event_state SET screen_dark_mode=$1,updated_at=now() WHERE id=1', [darkMode]); changed(io, 'screen:theme-changed'); }
export async function screen(view, io) { const views = ['WELCOME', 'WAITING', 'TEAM_OVERVIEW', 'SPEAKER_LEADERBOARD', 'SCENARIO_INTRO', 'SCENARIO_ACTIVE', 'SCENARIO_WAITING_FOR_ANSWERS', 'SCENARIO_VOTING', 'SCENARIO_RESULTS', 'SCENARIO_LEADERBOARD', 'FINAL_RESULTS']; if (!views.includes(view)) fail(400, 'Invalid general screen view.'); await pool.query('UPDATE event_state SET screen_view=$1,updated_at=now() WHERE id=1', [view]); changed(io, 'screen:view-changed'); }
export async function addSpeakerPrompts({ prompts }, io) { if (!Array.isArray(prompts) || !prompts.length || prompts.length > 100) fail(400, 'Add between 1 and 100 prompts at a time.'); const unique = new Map(); for (const value of prompts) { const prompt = validText(value, 500, 'Prompt'); unique.set(prompt.toLocaleLowerCase(), prompt); } const added = await tx(async db => { let count = 0; for (const prompt of unique.values()) { const result = await db.query('INSERT INTO speaker_prompts(prompt_text) VALUES($1) ON CONFLICT DO NOTHING RETURNING id', [prompt]); count += result.rowCount; } return count; }); if (!added) fail(409, 'All of these prompts are already in the bank.'); changed(io, 'speaker-prompts:changed'); return { added }; }
export async function deleteSpeakerPrompt(id, io) { const result = await pool.query('DELETE FROM speaker_prompts p WHERE p.id=$1 AND NOT EXISTS(SELECT 1 FROM speaker_sessions ss WHERE ss.prompt_id=p.id) RETURNING p.id', [needId(id)]); if (!result.rowCount) fail(409, 'A prompt cannot be deleted after it has been assigned to a team.'); changed(io, 'speaker-prompts:changed'); }

export async function selectSpeaker({ teamId, attendeeId }, io) { await tx(async db => { const id = needTeamId(teamId), state = await locked(db), teamState = await teamSpeakerState(db, id, true); if (state.activity === 'SCENARIO') fail(409, 'Finish or cancel the scenario round first.'); if (teamState.speaker_session_id) fail(409, "Finish or cancel this team's current speaker round first."); const prompt = await one(db, 'SELECT p.id,p.prompt_text FROM speaker_prompts p WHERE NOT EXISTS(SELECT 1 FROM speaker_sessions ss WHERE ss.prompt_id=p.id AND ss.team_id=$1) ORDER BY random() LIMIT 1 FOR UPDATE OF p', [id]); if (!prompt) fail(409, 'This team has used every prompt. Add more prompts to the bank.'); let chosen; if (attendeeId) { chosen = await attendee(db, attendeeId); if (chosen.team_id !== id) fail(400, 'Attendee is on another team.'); } else chosen = selectRandom(await all(db, "SELECT a.* FROM attendees a WHERE a.team_id=$1 AND NOT EXISTS(SELECT 1 FROM speaker_sessions ss WHERE ss.speaker_id=a.id AND ss.status<>'CANCELLED')", [id]))[0]; const speaker = await one(db, 'INSERT INTO speaker_sessions(speaker_id,team_id,prompt_id,status) VALUES($1,$2,$3,$4) RETURNING id', [chosen.id, chosen.team_id, prompt.id, 'SELECTED']); await db.query("UPDATE team_speaker_state SET speaker_session_id=$2,screen_view='SPEAKER_SELECTION',updated_at=now() WHERE team_id=$1", [id, speaker.id]); await db.query("UPDATE event_state SET activity='SPEAKER',speaker_session_id=NULL,updated_at=now() WHERE id=1"); }); changed(io, 'speaker:selected'); }
export async function confirmSpeaker(token, id, io) { await tx(async db => { if (!uuid(token)) fail(403, 'This QR code is not assigned to you or has expired.'); const speaker = await one(db, 'SELECT * FROM speaker_sessions WHERE qr_token=$1', [token]); if (!speaker) fail(403, 'This QR code is not assigned to you or has expired.'); const teamState = await teamSpeakerState(db, speaker.team_id, true); if (teamState.speaker_session_id !== speaker.id) fail(403, 'This QR code is no longer active.'); requireStatus(speaker.status, ['SELECTED']); if (new Date(speaker.qr_expires_at) < new Date() || speaker.speaker_id !== needId(id)) fail(403, 'This QR code is not assigned to you or has expired.'); await db.query("UPDATE speaker_sessions SET status='CONFIRMED' WHERE id=$1", [speaker.id]); await db.query("UPDATE team_speaker_state SET screen_view='SPEAKER_ACTIVE',updated_at=now() WHERE team_id=$1", [speaker.team_id]); }); changed(io, 'speaker:confirmed'); }
export async function speakerTransition(action, { teamId } = {}, io) { await tx(async db => { await locked(db); const teamState = await teamSpeakerState(db, teamId, true), speaker = await currentSpeaker(db, teamState), rules = { open: [['CONFIRMED', 'CLOSED'], 'OPEN', 'SPEAKER_VOTING'], close: [['OPEN'], 'CLOSED', 'SPEAKER_VOTING'], reveal: [['CLOSED'], 'REVEALED', 'SPEAKER_RESULT'], 'force-reveal': [['OPEN'], 'REVEALED', 'SPEAKER_RESULT'], cancel: [['SELECTED', 'CONFIRMED', 'OPEN', 'CLOSED'], 'CANCELLED', 'WAITING'] }, rule = rules[action]; if (!rule) fail(400, 'Invalid action.'); requireStatus(speaker.status, rule[0]); let result = null; if (action === 'reveal' || action === 'force-reveal') result = score((await all(db, 'SELECT rating FROM speaker_votes WHERE session_id=$1', [speaker.id])).map(item => item.rating)); await db.query('UPDATE speaker_sessions SET status=$2,displayed_score=$3 WHERE id=$1', [speaker.id, rule[1], result]); await db.query('UPDATE team_speaker_state SET screen_view=$2,speaker_session_id=$3,updated_at=now() WHERE team_id=$1', [speaker.team_id, rule[2], action === 'cancel' ? null : speaker.id]); if (action === 'cancel') { const active = (await one(db, 'SELECT count(*)::int AS count FROM team_speaker_state WHERE speaker_session_id IS NOT NULL')).count; await db.query('UPDATE event_state SET activity=$1,updated_at=now() WHERE id=1', [active ? 'SPEAKER' : 'NONE']); } }); changed(io, `speaker:${action}`); }
export async function speakerVote({ attendeeId, rating }, io) { const value = Number(rating); if (!Number.isInteger(value) || value < 0 || value > 100) fail(400, 'Rating must be 0–100.'); await tx(async db => { const person = await attendee(db, attendeeId), teamState = await teamSpeakerState(db, person.team_id, true), speaker = await currentSpeaker(db, teamState); requireStatus(speaker.status, ['OPEN']); if (person.id === speaker.speaker_id) fail(403, 'A speaker cannot rate themselves.'); try { await db.query('INSERT INTO speaker_votes(session_id,attendee_id,rating) VALUES($1,$2,$3)', [speaker.id, person.id, value]); } catch (error) { if (error.code === '23505') fail(409, 'You already rated this speaker.'); throw error; } }); changed(io, 'speaker:vote-count-updated'); }

export async function saveScenario({ id, title, text, status }, io) { if (!['DRAFT', 'READY'].includes(status)) fail(400, 'Invalid scenario status.'); const result = id ? await one(pool, "UPDATE scenarios SET title=$2,scenario_text=$3,status=$4 WHERE id=$1 AND status IN ('DRAFT','READY') RETURNING *", [needId(id), validText(title, 100, 'Title'), validText(text, 2000, 'Scenario'), status]) : await one(pool, 'INSERT INTO scenarios(title,scenario_text,status) VALUES($1,$2,$3) RETURNING *', [validText(title, 100, 'Title'), validText(text, 2000, 'Scenario'), status]); if (!result) fail(409, 'Scenario cannot be edited now.'); changed(io); return result; }
export async function deleteScenario(id, io) { const result = await pool.query("DELETE FROM scenarios WHERE id=$1 AND status IN ('DRAFT','READY') RETURNING id", [needId(id)]); if (!result.rowCount) fail(409, 'Scenario cannot be deleted now.'); changed(io); }
export async function startScenario({ scenarioId, durationSeconds }, io) { const duration = Number(durationSeconds); if (!Number.isInteger(duration) || duration < 10 || duration > 3600) fail(400, 'Choose an answer time between 10 seconds and 60 minutes.'); const round = await tx(async db => { const state = await locked(db), activeSpeakers = (await one(db, 'SELECT count(*)::int AS count FROM team_speaker_state WHERE speaker_session_id IS NOT NULL')).count; if (state.activity !== 'NONE' || activeSpeakers) fail(409, 'Finish or cancel all current rounds first.'); const scenario = await one(db, 'SELECT * FROM scenarios WHERE id=$1', [needId(scenarioId)]); if (!scenario || scenario.status !== 'READY') fail(409, 'Choose a ready scenario.'); const created = await one(db, "INSERT INTO scenario_rounds(scenario_id,status,duration_seconds,started_at,ends_at) VALUES($1,'COLLECTING',$2::integer,now(),now()+($2::integer*interval '1 second')) RETURNING id,ends_at", [scenario.id, duration]); await db.query('INSERT INTO scenario_round_participants(round_id,attendee_id) SELECT $1,id FROM attendees ON CONFLICT DO NOTHING', [created.id]); await db.query("UPDATE scenarios SET status='ACTIVE' WHERE id=$1", [scenario.id]); await db.query("UPDATE event_state SET activity='SCENARIO',scenario_round_id=$1,speaker_session_id=NULL,screen_view='SCENARIO_WAITING_FOR_ANSWERS',updated_at=now() WHERE id=1", [created.id]); return created; }); changed(io, 'scenario:started'); const delay = Math.max(0, new Date(round.ends_at).getTime() - Date.now()) + 50; const timer = setTimeout(async () => { try { if (await advanceExpiredScenario()) changed(io, 'scenario:voting-opened'); } catch { /* a client refresh will retry the deadline transition */ } }, delay); timer.unref?.(); }
export async function submitAnswer({ attendeeId, text }, io) { await advanceExpiredScenario(); await tx(async db => { const state = await locked(db), round = await currentRound(db, state); requireStatus(round.status, ['COLLECTING']); if (new Date(round.ends_at).getTime() <= Date.now()) fail(409, 'Answer time has ended.'); const person = await attendee(db, attendeeId); if (!await one(db, 'SELECT 1 FROM scenario_round_participants WHERE round_id=$1 AND attendee_id=$2', [round.id, person.id])) fail(403, 'This round started before you joined.'); const order = (await one(db, 'SELECT count(*)::int AS n FROM scenario_answers WHERE round_id=$1', [round.id])).n; try { await db.query('INSERT INTO scenario_answers(round_id,attendee_id,answer_text,display_order) VALUES($1,$2,$3,$4)', [round.id, person.id, validText(text, 2000, 'Answer'), order]); } catch (error) { if (error.code === '23505') fail(409, 'Your answer is already submitted.'); throw error; } }); changed(io, 'scenario:answer-submitted'); }
export async function scenarioTransition(action, io) { await advanceExpiredScenario(); await tx(async db => { const state = await locked(db), round = await currentRound(db, state), rules = { open: [['COLLECTING', 'CLOSED'], 'OPEN', 'SCENARIO_VOTING'], close: [['OPEN'], 'CLOSED', 'SCENARIO_VOTING'], reveal: [['CLOSED'], 'REVEALED', 'SCENARIO_RESULTS'], 'force-reveal': [['OPEN'], 'REVEALED', 'SCENARIO_RESULTS'], cancel: [['COLLECTING', 'OPEN', 'CLOSED'], 'CANCELLED', 'WAITING'] }, rule = rules[action]; if (!rule) fail(400, 'Invalid action.'); requireStatus(round.status, rule[0]); if (action === 'open' && round.status === 'COLLECTING') await randomizeScenarioAnswers(db, round.id); await db.query('UPDATE scenario_rounds SET status=$2 WHERE id=$1', [round.id, rule[1]]); if (['reveal', 'force-reveal', 'cancel'].includes(action)) await db.query('UPDATE scenarios SET status=$2 WHERE id=$1', [round.scenario_id, action === 'cancel' ? 'READY' : 'COMPLETED']); await db.query('UPDATE event_state SET activity=$1,scenario_round_id=$2,screen_view=$3,updated_at=now() WHERE id=1', [action === 'cancel' ? 'NONE' : 'SCENARIO', action === 'cancel' ? null : round.id, rule[2]]); }); changed(io, `scenario:${action}`); }
export async function finishActivity({ teamId } = {}, io) { await tx(async db => { const state = await locked(db); if (teamId != null) { const teamState = await teamSpeakerState(db, teamId, true), speaker = await currentSpeaker(db, teamState); requireStatus(speaker.status, ['REVEALED']); await db.query("UPDATE team_speaker_state SET speaker_session_id=NULL,screen_view='WAITING',updated_at=now() WHERE team_id=$1", [speaker.team_id]); const active = (await one(db, 'SELECT count(*)::int AS count FROM team_speaker_state WHERE speaker_session_id IS NOT NULL')).count; await db.query('UPDATE event_state SET activity=$1,updated_at=now() WHERE id=1', [active ? 'SPEAKER' : 'NONE']); return; } if (state.activity !== 'SCENARIO') fail(409, 'No completed scenario activity.'); const round = await currentRound(db, state); requireStatus(round.status, ['REVEALED']); await db.query("UPDATE event_state SET activity='NONE',scenario_round_id=NULL,screen_view='WAITING',updated_at=now() WHERE id=1"); }); changed(io); }
export async function scenarioVote({ attendeeId, answerId }, io) { await advanceExpiredScenario(); await tx(async db => { const state = await locked(db), round = await currentRound(db, state); requireStatus(round.status, ['OPEN']); const person = await attendee(db, attendeeId); const answer = await one(db, 'SELECT id,attendee_id FROM scenario_answers WHERE id=$1 AND round_id=$2', [needId(answerId), round.id]); if (!answer) fail(400, 'Answer is unavailable.'); if (answer.attendee_id === person.id) fail(403, 'You cannot vote for your own answer.'); try { await db.query('INSERT INTO scenario_votes(round_id,attendee_id,answer_id) VALUES($1,$2,$3)', [round.id, person.id, answer.id]); } catch (error) { if (error.code === '23505') fail(409, 'You already voted in this round.'); throw error; } }); changed(io, 'scenario:vote-count-updated'); }
