import test from 'node:test';
import assert from 'node:assert/strict';

test('PostgreSQL registration, isolated speaker rounds and scenario integrity', { skip: !process.env.TEST_DATABASE_URL }, async () => {
  const dbUrl = new URL(process.env.TEST_DATABASE_URL);
  if (!dbUrl.pathname.endsWith('_test')) throw new Error('TEST_DATABASE_URL must name a dedicated *_test database.');
  process.env.DATABASE_URL = process.env.TEST_DATABASE_URL;
  process.env.ADMIN_PASSWORD = 'integration-test-password';
  const { pool, initDb } = await import('../db/index.js');
  const event = await import('./event.js');
  const { login, session } = await import('../auth.js');
  const io = { emit() {} };
  try {
    await initDb();
    await pool.query('TRUNCATE team_speaker_state,speaker_votes,scenario_votes,scenario_answers,scenario_round_participants,scenario_rounds,speaker_sessions,speaker_prompts,scenarios,attendees,admin_sessions RESTART IDENTITY CASCADE');
    await pool.query('INSERT INTO event_state(id) VALUES(1) ON CONFLICT(id) DO NOTHING');
    await pool.query("UPDATE event_state SET activity='NONE',speaker_session_id=NULL,scenario_round_id=NULL,screen_view='WELCOME'");
    await pool.query('INSERT INTO team_speaker_state(team_id) VALUES(1),(2)');

    const alice = await event.register({ name: 'Alice One', teamId: 1 });
    const bob = await event.register({ name: 'Bob Two', teamId: 1 });
    const cara = await event.register({ name: 'Cara Three', teamId: 2 });
    const dan = await event.register({ name: 'Dan Four', teamId: 2 });
    const eve = await event.register({ name: 'Eve Five', teamId: 2 });
    await assert.rejects(event.register({ name: ' alice  one ', teamId: 2 }), /already registered/);
    assert.equal((await event.getAttendee(alice.id)).id, alice.id);
    assert.deepEqual(await event.addSpeakerPrompts({ prompts: ['Explain a lesson you learned the hard way.'] }, io), { added: 1 });

    await event.selectSpeaker({ teamId: 1, attendeeId: alice.id }, io);
    await event.selectSpeaker({ teamId: 2, attendeeId: cara.id }, io);
    await assert.rejects(event.deactivateAttendee(alice.id, io), /active speaker/);
    let state = await event.publicState(alice.id, 'http://localhost:5173');
    assert.equal(state.speaker.qrUrl, undefined);
    const firstPrompt = state.speaker.prompt;
    let adminState = await event.adminSnapshot('http://localhost:5173');
    assert.equal(adminState.speakers.length, 2);
    assert.equal((await event.publicState(null, 'http://localhost:5173', false, 1)).speaker.name, 'Alice One');
    assert.equal((await event.publicState(null, 'http://localhost:5173', false, 2)).speaker.name, 'Cara Three');
    assert.equal(adminState.speakers.find(speaker => speaker.teamId === 1).prompt, adminState.speakers.find(speaker => speaker.teamId === 2).prompt);
    const teamOne = adminState.speakers.find(speaker => speaker.teamId === 1);
    const token = new URL(teamOne.qrUrl).searchParams.get('confirm');
    await assert.rejects(event.confirmSpeaker(token, bob.id, io), /not assigned/);
    await event.confirmSpeaker(token, alice.id, io);
    const confirmedTeamOneScreen = await event.publicState(null, 'http://localhost:5173', false, 1);
    const untouchedTeamTwoScreen = await event.publicState(null, 'http://localhost:5173', false, 2);
    assert.equal(confirmedTeamOneScreen.screenView, 'SPEAKER_ACTIVE');
    assert.equal(confirmedTeamOneScreen.speaker.name, 'Alice One');
    assert.equal(confirmedTeamOneScreen.speaker.prompt, firstPrompt);
    assert.equal(untouchedTeamTwoScreen.screenView, 'SPEAKER_SELECTION');
    await event.speakerTransition('open', { teamId: 1 }, io);
    state = await event.publicState(bob.id, 'http://localhost:5173');
    assert.equal(state.speaker.canVote, true);
    state = await event.publicState(cara.id, 'http://localhost:5173');
    assert.equal(state.speaker.name, 'Cara Three');
    await assert.rejects(event.speakerVote({ attendeeId: alice.id, rating: 80 }, io), /cannot rate themselves/);
    await event.speakerVote({ attendeeId: bob.id, rating: 80 }, io);
    await assert.rejects(event.speakerVote({ attendeeId: bob.id, rating: 90 }, io), /already rated/);
    await event.speakerTransition('close', { teamId: 1 }, io);
    await event.speakerTransition('reveal', { teamId: 1 }, io);
    state = await event.publicState(bob.id, 'http://localhost:5173');
    assert.equal(state.speaker.score, 90);
    await event.finishActivity({ teamId: 1 }, io);
    assert.equal((await event.publicState(cara.id, 'http://localhost:5173')).speaker.name, 'Cara Three');
    await event.speakerTransition('cancel', { teamId: 2 }, io);

    assert.deepEqual(await event.addSpeakerPrompts({ prompts: ['Convince the audience to adopt a useful habit.'] }, io), { added: 1 });
    await event.selectSpeaker({ teamId: 1 }, io);
    state = await event.publicState(bob.id, 'http://localhost:5173');
    assert.equal(state.speaker.name, 'Bob Two');
    assert.notEqual(state.speaker.prompt, firstPrompt);
    const secondPrompt = (await event.adminSnapshot('http://localhost:5173')).speakerPrompts.find(prompt => prompt.prompt_text !== firstPrompt);
    await event.speakerTransition('cancel', { teamId: 1 }, io);
    await event.selectSpeaker({ teamId: 2, attendeeId: dan.id, promptId: secondPrompt.id }, io);
    state = await event.publicState(dan.id, 'http://localhost:5173');
    assert.equal(state.speaker.name, 'Dan Four');
    assert.equal(state.speaker.prompt, secondPrompt.prompt_text);
    await event.speakerTransition('cancel', { teamId: 2 }, io);
    adminState = await event.adminSnapshot('http://localhost:5173');
    assert.equal(adminState.speakerPrompts.reduce((total, prompt) => total + prompt.used_team_ids.length, 0), 4);
    assert.ok(adminState.speakerPrompts.every(prompt => prompt.used_team_ids.includes(1)));
    await assert.rejects(event.selectSpeaker({ teamId: 1 }, io), /used every prompt/);

    const scenario = await event.saveScenario({ title: 'The Challenge', text: 'What would you do?', status: 'READY' }, io);
    await event.startScenario({ scenarioId: scenario.id, durationSeconds: 60 }, io);
    state = await event.publicState(eve.id, 'http://localhost:5173');
    assert.equal(state.scenario.status, 'COLLECTING');
    assert.ok(state.scenario.endsAt);
    await event.submitAnswer({ attendeeId: alice.id, text: 'Answer from Alice' }, io);
    await assert.rejects(event.submitAnswer({ attendeeId: alice.id, text: 'Again' }, io), /already submitted/);
    await event.submitAnswer({ attendeeId: bob.id, text: 'Answer from Bob' }, io);
    await event.submitAnswer({ attendeeId: cara.id, text: 'Answer from Cara' }, io);
    await pool.query("UPDATE scenario_rounds SET ends_at=now()-interval '1 second' WHERE id=$1", [state.scenario.id]);
    state = await event.publicState(dan.id, 'http://localhost:5173');
    assert.equal(state.scenario.status, 'OPEN');
    assert.equal(state.scenario.answers.length, 3);
    assert.ok(state.scenario.answers.every(answer => !('attendee_id' in answer) && !answer.author));
    const aliceState = await event.publicState(alice.id, 'http://localhost:5173');
    const ownAnswer = aliceState.scenario.answers.find(answer => answer.is_own);
    const anotherAnswer = aliceState.scenario.answers.find(answer => !answer.is_own);
    assert.ok(ownAnswer);
    await assert.rejects(event.scenarioVote({ attendeeId: alice.id, answerId: ownAnswer.id }, io), /own answer/);
    await event.scenarioVote({ attendeeId: alice.id, answerId: anotherAnswer.id }, io);
    await event.scenarioVote({ attendeeId: dan.id, answerId: ownAnswer.id }, io);
    await event.scenarioTransition('force-reveal', io);
    state = await event.publicState(dan.id, 'http://localhost:5173');
    assert.equal(state.scenario.answers[0].votes, 1);
    assert.ok(state.scenario.answers.every(answer => answer.author));
    assert.equal(state.scenarioLeaderboard.reduce((sum, row) => sum + row.points, 0), 2);
    await event.finishActivity({}, io);

    const contentPack = await event.exportContentData();
    assert.deepEqual(Object.keys(contentPack).sort(), ['exportedAt', 'format', 'scenarios', 'speakerPrompts', 'version']);
    assert.equal(contentPack.format, 'gdg-live-event-content');
    assert.equal(contentPack.speakerPrompts.length, 2);
    assert.deepEqual(contentPack.scenarios, [{ title: 'The Challenge', text: 'What would you do?' }]);
    assert.deepEqual(await event.importContentData({ pack: contentPack }, io), { promptsAdded: 0, scenariosAdded: 0 });
    const expandedContentPack = { ...contentPack, speakerPrompts: [...contentPack.speakerPrompts, 'Describe a bold idea in sixty seconds.'], scenarios: [...contentPack.scenarios, { title: 'Community Challenge', text: 'How would you bring people together?' }] };
    assert.deepEqual(await event.importContentData({ pack: expandedContentPack }, io), { promptsAdded: 1, scenariosAdded: 1 });
    await assert.rejects(event.importContentData({ pack: await event.exportEventData() }, io), /valid prompts and scenarios export/);
    adminState = await event.adminSnapshot('http://localhost:5173');
    assert.equal(adminState.speakerPrompts.length, 3);
    assert.equal(adminState.scenarios.length, 2);

    await event.deactivateAttendee(alice.id, io);
    await assert.rejects(event.getAttendee(alice.id), /not found/);
    assert.equal((await event.publicState(alice.id, 'http://localhost:5173')).viewer, null);
    adminState = await event.adminSnapshot('http://localhost:5173');
    assert.equal(adminState.attendees.some(person => person.id === alice.id), false);
    const replacementAlice = await event.register({ name: 'Alice One', teamId: 2 });
    assert.notEqual(replacementAlice.id, alice.id);

    const req = { body: { password: 'wrong' } };
    await assert.rejects(login(req, { cookie() {}, json() {} }), /Incorrect password/);
    assert.equal(await session({ signedCookies: {} }), false);
    void eve;
  } finally { await pool.end(); }
});
