import React,{useCallback,useEffect,useState} from 'react';
import QRCode from 'qrcode';
import {api,subscribe} from './api.js';
import {Brand,Busy,palette,Pill,Shell} from './components/UI.jsx';

const GOOGLE=['#4285F4','#EA4335','#FBBC04','#34A853'];

export default function Screen({darkMode:initialDarkMode=false,teamId=null}){
  const [data,setData]=useState(null);
  const [offline,setOffline]=useState(false);
  const refresh=useCallback(()=>api(`/state${teamId?`?screenTeamId=${teamId}`:''}`).then(next=>{setData(next);setOffline(false)}).catch(()=>setOffline(true)),[teamId]);
  useEffect(()=>{refresh();const stop=subscribe(refresh);const poll=setInterval(refresh,15000);return()=>{stop();clearInterval(poll)}},[refresh]);
  const darkMode=data?.screenDarkMode??initialDarkMode;
  useEffect(()=>{document.documentElement.classList.toggle('dark',darkMode)},[darkMode]);
  useEffect(()=>{const r=data?.scenario;if(r?.status!=='COLLECTING'||!r.endsAt)return;const timer=setTimeout(refresh,Math.max(0,new Date(r.endsAt).getTime()-Date.now())+150);return()=>clearTimeout(timer)},[data?.scenario?.status,data?.scenario?.endsAt,refresh]);
  if(!data)return <Shell darkMode={darkMode}><div className="min-h-[calc(100vh-4px)] flex items-center justify-center"><Busy darkMode={darkMode}/></div></Shell>;

  const t=palette(darkMode),sp=data.speaker,sc=data.scenario,view=data.screenView,screenTeam=teamId?data.teams.find(team=>team.id===teamId):null;
  const byTeam=data.teams.map(team=>({team,rows:data.speakerLeaderboard.filter(x=>x.team_id===team.id)}));
  const teamAverage=byTeam.map(x=>({team:x.team,average:data.teamPerformance.find(y=>y.team_id===x.team.id)?.average??null,best:x.rows[0]}));
  const topAverage=Math.max(...teamAverage.map(x=>x.average??-1));
  let scene={kicker:'GDG KAU · LIVE',title:data.eventName,description:'Join from your phone and be part of the room.',content:<JoinQR darkMode={darkMode}/>,tone:'#3A7CF5'};

  if(view==='WAITING')scene={kicker:teamId?`${screenTeam?.name||`TEAM ${teamId}`} · SPEAKER ROUNDS`:'UP NEXT',title:teamId?'Ready for the next speaker.':'The room is ready.',description:teamId?'This screen is dedicated to this team’s speaker rounds.':'The next activity will appear here automatically.',content:<BrandDots/>,tone:screenTeam?.color||'#3A7CF5'};
  if(view==='TEAM_OVERVIEW')scene={kicker:'MEET THE TEAMS',title:'One stage. Two teams.',description:'Every voice has a part to play.',content:<div className="grid md:grid-cols-2 gap-5 w-full">{data.teams.map(team=><TeamCard key={team.id} team={team} darkMode={darkMode}/>)}</div>,tone:'#4285F4'};
  if(['SPEAKER_SELECTION','SPEAKER_QR'].includes(view))scene={kicker:'SPEAKER CHECK-IN',title:'Next speaker, check in.',description:'Please scan the private QR at the control desk. Your name will appear here once confirmed.',content:<CheckInStatus darkMode={darkMode}/>,tone:'#FBBC04'};
  if(view==='SPEAKER_ACTIVE'&&sp)scene={kicker:'NOW ON STAGE',title:sp.name,description:sp.teamName,content:<SpeakerMark speaker={sp} darkMode={darkMode}/>,tone:sp.teamColor};
  if(view==='SPEAKER_VOTING'&&sp)scene={kicker:'TEAM VOTING',title:'Voting is open.',description:`Only ${sp.teamName} members can rate ${sp.name}.`,content:<VoteStatus speaker={sp} darkMode={darkMode}/>,tone:'#3A7CF5'};
  if(view==='SPEAKER_RESULT'&&sp)scene={kicker:'SPEAKER RESULT',title:sp.name,description:sp.teamName,content:<Score value={sp.score} color={sp.teamColor} darkMode={darkMode}/>,tone:sp.teamColor};
  if(view==='SPEAKER_LEADERBOARD')scene={kicker:'SPEAKER COMPETITION',title:'Leaderboard',description:'Top speakers from each team.',content:<div className="grid md:grid-cols-2 gap-5 w-full">{byTeam.map(x=><LeaderboardCard key={x.team.id} team={x.team} rows={x.rows} darkMode={darkMode}/>)}</div>,tone:'#3A7CF5'};
  if(['SCENARIO_INTRO','SCENARIO_ACTIVE','SCENARIO_WAITING_FOR_ANSWERS'].includes(view)&&sc)scene={kicker:'SCENARIO CHALLENGE',title:sc.title,description:sc.text,content:view==='SCENARIO_INTRO'?<BrandDots/>:<ScenarioTimer endsAt={sc.endsAt} darkMode={darkMode}/>,tone:'#FBBC04'};
  if(view==='SCENARIO_VOTING'&&sc)scene={kicker:'AUDIENCE VOTING',title:'Choose the best answer.',description:sc.title,content:<Metric value={sc.answers.length} label="anonymous answers" darkMode={darkMode}/>,tone:'#3A7CF5'};
  if(view==='SCENARIO_RESULTS'&&sc)scene={kicker:'SCENARIO RESULTS',title:sc.title,description:'The voices behind the answers.',content:<ScenarioResults answers={sc.answers} darkMode={darkMode}/>,tone:'#34A853'};
  if(view==='SCENARIO_LEADERBOARD')scene={kicker:'SCENARIO CHALLENGE',title:'Leaderboard',description:'Cumulative points across all rounds.',content:<ScenarioLeaderboard rows={data.scenarioLeaderboard} darkMode={darkMode}/>,tone:'#34A853'};
  if(view==='FINAL_RESULTS')scene={kicker:'THE FINAL MOMENT',title:'What a night.',description:'Celebrating everyone who took the stage.',content:<FinalResults teams={teamAverage} topAverage={topAverage} scenarioWinner={data.scenarioLeaderboard[0]} darkMode={darkMode}/>,tone:'#3A7CF5'};

  return <Shell darkMode={darkMode} className="h-screen overflow-hidden"><div className="relative min-h-[calc(100vh-4px)] flex flex-col overflow-hidden px-[clamp(24px,4vw,72px)] py-[clamp(22px,3vh,38px)]"><Backdrop darkMode={darkMode} tone={scene.tone}/><header className="relative z-10 flex items-center justify-between"><Brand darkMode={darkMode}/><div className="flex items-center gap-3">{screenTeam&&<Pill darkMode={darkMode} color={screenTeam.color}>{screenTeam.name.toUpperCase()} SCREEN</Pill>}<span className="hidden sm:block text-[12px] font-['Roboto']" style={{color:t.muted}}>{darkMode?'Dark screen':'Light screen'}</span><Pill kind={offline?'warning':'success'} darkMode={darkMode}>{offline?'RECONNECTING':'LIVE'}</Pill></div></header><main className="relative z-10 flex-1 min-h-0 grid lg:grid-cols-[minmax(0,.82fr)_minmax(420px,1.18fr)] gap-[clamp(28px,5vw,84px)] items-center py-[3vh]"><div className="text-left"><div className="inline-flex items-center gap-3 font-['Roboto'] text-[clamp(11px,1vw,15px)] font-bold tracking-[.2em] mb-5" style={{color:scene.tone}}><span className="w-9 h-[3px] rounded-full" style={{background:scene.tone}}/>{scene.kicker}</div><h1 className="font-['DM_Sans'] font-bold tracking-[-.055em] leading-[.96] text-[clamp(48px,7.2vw,118px)] max-w-[900px]">{scene.title}</h1><p className="font-['Roboto'] text-[clamp(17px,1.75vw,28px)] leading-[1.45] max-w-3xl mt-6" style={{color:t.muted}}>{scene.description}</p></div><div className="w-full max-h-[68vh] overflow-hidden flex items-center justify-center">{scene.content}</div></main><footer className="relative z-10 flex justify-between items-center gap-5 font-['Roboto'] text-[12px] sm:text-[14px]" style={{color:t.muted}}><span>GDG KAU</span><span>{screenTeam?`${screenTeam.name} · Speaker rounds`:'Connect · Speak · Inspire'}</span></footer></div></Shell>;
}

function Backdrop({darkMode,tone}){return <div className="absolute inset-0 pointer-events-none overflow-hidden"><div className="absolute -right-[12vw] -top-[28vh] w-[60vw] h-[60vw] rounded-full" style={{border:`1px solid ${tone}`,opacity:darkMode?.18:.1}}/><div className="absolute -right-[4vw] -top-[15vh] w-[38vw] h-[38vw] rounded-full" style={{border:'1px solid #EA4335',opacity:darkMode?.13:.07}}/><div className="absolute -left-[12vw] -bottom-[42vh] w-[48vw] h-[48vw] rounded-full" style={{border:'1px solid #34A853',opacity:darkMode?.13:.07}}/><div className="absolute top-0 left-0 right-0 h-[2px] flex">{GOOGLE.map(color=><span key={color} className="flex-1" style={{background:color}}/>)}</div></div>}
function Surface({darkMode,children,className=''}){const t=palette(darkMode);return <div className={`rounded-[24px] border ${className}`} style={{background:darkMode?'rgba(30,30,30,.92)':'rgba(255,255,255,.94)',borderColor:t.border,boxShadow:darkMode?'0 24px 70px rgba(0,0,0,.28)':'0 24px 70px rgba(32,33,36,.09)'}}>{children}</div>}
function BrandDots(){return <div className="flex gap-4 p-8">{GOOGLE.map((color,index)=><span key={color} className="w-5 h-5 rounded-full" style={{background:color,animation:`loadingDotsBounce .8s ${index*.15}s infinite`}}/>)}</div>}
function JoinQR({darkMode}){const [url,setUrl]=useState('');useEffect(()=>{QRCode.toDataURL(`${location.origin}/`,{width:520,margin:2,color:{dark:'#1C1B1F',light:'#FFFFFF'}}).then(setUrl)},[]);return <Surface darkMode={darkMode} className="p-5 sm:p-6 w-full max-w-[560px]"><div className="flex flex-col lg:flex-row items-center gap-4 lg:gap-5"><div className="bg-white p-2 rounded-[16px] w-[min(46vw,180px)] lg:w-[200px] aspect-square flex-shrink-0">{url?<img src={url} alt="Join event QR" className="w-full h-full"/>:<Busy darkMode={false}/>}</div><div className="min-w-0 text-center lg:text-left"><div className="font-['DM_Sans'] text-[clamp(22px,2.2vw,34px)] font-bold lg:whitespace-nowrap">Join the room</div><p className="font-['Roboto'] text-[clamp(13px,1.2vw,18px)] leading-relaxed mt-2 max-w-[32ch]" style={{color:palette(darkMode).muted}}>Scan once to vote and take part in every activity.</p></div></div></Surface>}
function CheckInStatus({darkMode}){const t=palette(darkMode);return <Surface darkMode={darkMode} className="p-[clamp(28px,4vw,60px)] w-full max-w-[620px]"><div className="flex items-center gap-6"><div className="w-20 h-20 rounded-[20px] flex items-center justify-center flex-shrink-0" style={{background:darkMode?'rgba(251,188,4,.15)':'#FFF8E1',color:'#E6A700'}}><svg width="38" height="38" viewBox="0 0 38 38" fill="none"><path d="M6 14V8a2 2 0 0 1 2-2h6M24 6h6a2 2 0 0 1 2 2v6M32 24v6a2 2 0 0 1-2 2h-6M14 32H8a2 2 0 0 1-2-2v-6" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round"/><path d="M12 19h14M19 12v14" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round"/></svg></div><div><div className="font-['DM_Sans'] text-[clamp(24px,3vw,42px)] font-bold">Waiting for scan</div><p className="font-['Roboto'] text-[clamp(14px,1.25vw,18px)] mt-2" style={{color:t.muted}}>Confirmation happens at the dashboard.</p></div></div></Surface>}
function SpeakerMark({speaker,darkMode}){const t=palette(darkMode);return <Surface darkMode={darkMode} className="p-[clamp(26px,4vw,52px)] w-full max-w-[680px] text-center"><div className="w-[clamp(82px,9vw,128px)] aspect-square rounded-full mx-auto flex items-center justify-center text-white font-['DM_Sans'] text-[clamp(26px,3.5vw,46px)] font-bold" style={{background:speaker.teamColor,boxShadow:`0 18px 46px ${speaker.teamColor}44`}}>{initials(speaker.name)}</div>{speaker.prompt&&<div className="mt-6 rounded-[16px] border p-5 text-left" style={{background:darkMode?'rgba(251,188,4,.15)':'#FFF8E1',borderColor:darkMode?'rgba(251,188,4,.35)':'#FFE082'}}><div className="font-['Roboto'] text-[12px] font-bold uppercase tracking-[.16em] mb-2" style={{color:darkMode?'#FBBF24':'#E65100'}}>Speaking prompt</div><p className="font-['DM_Sans'] text-[clamp(19px,2vw,28px)] font-semibold leading-snug">{speaker.prompt}</p></div>}<div className="mt-5 inline-flex items-center gap-2 rounded-full px-4 py-2 font-['Roboto'] text-[14px]" style={{background:t.alt,color:t.muted}}><span className="w-2 h-2 rounded-full bg-[#34A853] animate-live-pulse"/>Microphone is live</div></Surface>}
function VoteStatus({speaker,darkMode}){const t=palette(darkMode);return <Surface darkMode={darkMode} className="p-[clamp(26px,4vw,56px)] w-full max-w-[680px]"><div className="flex justify-between items-end gap-5"><div><div className="font-['Roboto'] text-[13px] uppercase tracking-[.16em]" style={{color:t.muted}}>Rate the speaker</div><div className="font-['DM_Sans'] text-[clamp(28px,3.5vw,52px)] font-bold mt-1">0—100</div></div><div className="text-right"><div className="font-['DM_Sans'] text-[clamp(38px,5vw,72px)] font-bold leading-none" style={{color:'#3A7CF5'}}>{speaker.voteCount}</div><div className="font-['Roboto'] text-[13px] mt-1" style={{color:t.muted}}>votes submitted</div></div></div><div className="mt-8"><div className="h-3 rounded-full overflow-hidden" style={{background:t.alt}}><div className="h-full w-full rounded-full screen-vote-shimmer"/></div><div className="flex justify-between mt-2 font-['JetBrains_Mono'] text-[12px]" style={{color:t.muted}}><span>0</span><span>50</span><span>100</span></div></div></Surface>}
function Score({value,color,darkMode}){const t=palette(darkMode);return <Surface darkMode={darkMode} className="p-[clamp(28px,4vw,60px)] w-full max-w-[650px] text-center"><div className="score-reveal font-['DM_Sans'] font-bold text-[clamp(110px,16vw,230px)] leading-[.85] tracking-[-.07em]" style={{color}}>{Math.round(value)}<span className="text-[.35em] tracking-normal">%</span></div><div className="mt-7 font-['Roboto'] text-[16px]" style={{color:t.muted}}>Audience score</div></Surface>}
function Metric({value,label,darkMode}){const t=palette(darkMode);return <Surface darkMode={darkMode} className="p-10 w-full max-w-[440px] text-center"><div className="font-['DM_Sans'] text-[90px] font-bold leading-none text-[#3A7CF5]">{value}</div><div className="font-['Roboto'] text-[18px] mt-3" style={{color:t.muted}}>{label}</div></Surface>}
function ScenarioTimer({endsAt,darkMode}){const t=palette(darkMode),[remaining,setRemaining]=useState(()=>Math.max(0,new Date(endsAt).getTime()-Date.now()));useEffect(()=>{const update=()=>setRemaining(Math.max(0,new Date(endsAt).getTime()-Date.now()));update();const timer=setInterval(update,250);return()=>clearInterval(timer)},[endsAt]);const seconds=Math.ceil(remaining/1000),minutes=Math.floor(seconds/60),rest=seconds%60,ending=seconds<=10;return <Surface darkMode={darkMode} className="p-[clamp(26px,4vw,52px)] w-full max-w-[600px] text-center"><div className="font-['Roboto'] text-[13px] uppercase tracking-[.16em]" style={{color:t.muted}}>Time left to submit</div><div className="font-['JetBrains_Mono'] text-[clamp(74px,11vw,150px)] font-bold leading-none mt-5 tabular-nums" style={{color:ending?'#EA4335':'#E6A700'}}>{minutes}:{String(rest).padStart(2,'0')}</div><div className="mt-6 inline-flex items-center gap-2 px-4 py-2 rounded-full font-['Roboto'] text-[14px]" style={{background:t.alt,color:t.muted}}><span className="w-2 h-2 rounded-full bg-[#34A853] animate-live-pulse"/>Both teams can answer now</div></Surface>}
function TeamCard({team,darkMode}){const t=palette(darkMode);return <Surface darkMode={darkMode} className="p-8 min-h-48 flex flex-col justify-between"><span className="w-12 h-2 rounded-full" style={{background:team.color}}/><div className="font-['DM_Sans'] font-bold text-[clamp(32px,4vw,58px)] mt-10" style={{color:team.color}}>{team.name}</div><div className="font-['Roboto'] text-[14px] mt-2" style={{color:t.muted}}>Team on stage</div></Surface>}
function LeaderboardCard({team,rows,darkMode}){const t=palette(darkMode);return <Surface darkMode={darkMode} className="p-7"><div className="flex items-center justify-between gap-4 mb-4"><h2 className="font-['DM_Sans'] text-[28px] font-bold" style={{color:team.color}}>{team.name}</h2><span className="w-9 h-2 rounded-full" style={{background:team.color}}/></div>{rows.length?rows.slice(0,5).map((row,index)=><div key={`${row.name}-${index}`} className="flex items-center gap-4 py-3 border-t" style={{borderColor:t.border}}><span className="w-8 text-center font-['DM_Sans'] font-bold" style={{color:t.muted}}>{index+1}</span><span className="font-['DM_Sans'] text-[clamp(16px,1.6vw,23px)] font-semibold truncate">{row.name}</span><strong className="ml-auto font-['DM_Sans'] text-[clamp(18px,2vw,28px)]" style={{color:team.color}}>{Math.round(row.score)}%</strong></div>):<p className="font-['Roboto'] py-8 text-center" style={{color:t.muted}}>Results appear after a reveal.</p>}</Surface>}
function ScenarioResults({answers,darkMode}){const t=palette(darkMode);return <div className="grid sm:grid-cols-2 gap-4 w-full">{answers.map((answer,index)=><Surface key={answer.id} darkMode={darkMode} className="p-5 flex justify-between gap-5"><div><div className="font-['DM_Sans'] text-[20px] font-bold">{index+1}. {answer.author}</div><p className="font-['Roboto'] text-[14px] mt-2 line-clamp-3" style={{color:t.muted}}>{answer.answer_text}</p></div><strong className="font-['DM_Sans'] text-[30px] text-[#3A7CF5]">{answer.votes}</strong></Surface>)}</div>}
function ScenarioLeaderboard({rows,darkMode}){const t=palette(darkMode);return <Surface darkMode={darkMode} className="p-7 w-full max-w-3xl">{rows.length?rows.slice(0,7).map((row,index)=><div key={`${row.name}-${index}`} className="flex items-center gap-4 py-3 border-b" style={{borderColor:t.border}}><span className="w-9 h-9 rounded-full flex items-center justify-center font-['DM_Sans'] font-bold" style={{background:t.alt}}>{index+1}</span><span className="font-['DM_Sans'] text-[22px] font-semibold">{row.name}</span><strong className="ml-auto font-['DM_Sans'] text-[24px] text-[#34A853]">{row.points} pts</strong></div>):<p className="font-['Roboto'] text-center py-10" style={{color:t.muted}}>Results appear after a reveal.</p>}</Surface>}
function FinalResults({teams,topAverage,scenarioWinner,darkMode}){const t=palette(darkMode);return <div className="grid lg:grid-cols-3 gap-4 w-full">{teams.map(x=><Surface key={x.team.id} darkMode={darkMode} className="p-6"><div className="font-['DM_Sans'] text-[20px] font-bold" style={{color:x.team.color}}>{x.team.name}</div>{x.average!==null&&x.average===topAverage&&<div className="font-['Roboto'] text-[12px] mt-1" style={{color:x.team.color}}>Top team average</div>}<div className="font-['Roboto'] text-[13px] mt-5" style={{color:t.muted}}>Best speaker</div><div className="font-['DM_Sans'] text-[22px] font-bold">{x.best?.name||'—'}</div><div className="font-['DM_Sans'] text-[42px] font-bold mt-4">{x.average==null?'—':`${Math.round(x.average)}%`}</div></Surface>)}<Surface darkMode={darkMode} className="p-6"><div className="font-['DM_Sans'] text-[20px] font-bold text-[#34A853]">Scenario winner</div><div className="font-['DM_Sans'] text-[26px] font-bold mt-8">{scenarioWinner?.name||'—'}</div><div className="font-['Roboto'] text-[17px] mt-2" style={{color:t.muted}}>{scenarioWinner?.points||0} points</div></Surface></div>}
function initials(name=''){return name.split(/\s+/).filter(Boolean).slice(0,2).map(part=>part[0]).join('').toUpperCase()}
